### ISSUE TITLE
Parser.extend is not a function

### ISSUE THREAD

**Issue by deligent-ant** [andrerpena/react-mde#250]
Parser.extend is not a function. when in ssr

**Comment by andrerpena** [comment]
Thanks for reporting. I will test with Next.js and see what happens

**Comment by deligent-ant** [comment]
thank you very much，the problem may caused by the package @mdx-js/runtime .but i still hope you can help me.
i combind your package with @mdx-js/runtime.

```js
acorn__WEBPACK_IMPORTED_MODULE_1__.Parser.extend is not a function

TypeError: acorn__WEBPACK_IMPORTED_MODULE_1__.Parser.extend is not a function 
at Module.../node_modules/buble-jsx-only/dist/buble-browser.es.js (http://0.0.0.0:3007/_next/static/chunks/2.js:70747:59) at __webpack_require__ 
(http://0.0.0.0:3007/_next/static/runtime/webpack.js:795:31) at fn (http://0.0.0.0:3007/_next/static/runtime/webpack.js:151:20) 


at Module.../node_modules/@mdx-js/runtime/dist/esm.js (http://0.0.0.0:3007/_next/static/chunks/2.js:66942:72) at 
_
