### ISSUE TITLE
New problems with installing deps and running

### ISSUE THREAD

**Issue by Nes-si** [andrerpena/react-mde#95]
Hi there.
Since today, I can't run the project. Probably it concerns with upgrading to Node 10.
If I run `npm install` on pure repo clone, I get an error with node-sass:
```
4 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/data_hfs/Code/web/3rd/react-mde/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/10.0.0/bin/node" "/Volumes/data_hfs/Code/web/3rd/react-mde/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Volumes/data_hfs/Code/web/3rd/react-mde/node_modules/node-sass
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nss/.npm/_logs/2018-04-26T21_28_32_049Z-debug.log
```
So `node-sass` and `gulp-sass` don't install.

If I remove `package-lock.json` and try again, npm finishes installation correctly. But when I run demo (`npm start`), I get there are 4 errors:
```
ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:2381:15 
    TS2300: Duplicate identifier 'URL'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:2399:15 
    TS2300: Duplicate identifier 'URLSearchParams'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:2417:14 
    TS2661: Cannot export 'URL'. Only local declarations can be exported from a module.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:2417:19 
    TS2661: Cannot export 'URLSearchParams'. Only local declarations can be exported from a module.
```

**Comment by andrerpena** [comment]
Thanks for reporting. Updating `node-sass` made it possible to run build `gulp-sass` is still broken so I cannot `npm run build` on Node 10 now.

I think I will ditch Gulp and just have a Make file. It is much simpler. People on Windows can now run Make with POSIX commands because Bash apparently works well on Windows now.

I'll keep you posted.

**Comment by andrerpena** [comment]
Also.. use https://github.com/creationix/nvm if you don't already =)
